name: ci

on:
  push:
    paths:
      - docker/**

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get neon-query-bench version
        id: get_nqb_version
        run: |
          echo "version=$(jq -e -r '.dependencies["neon-query-bench"] // empty | select(. != null)' docker/package.json)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: evanatneon/neon-query-bench:latest,evanatneon/neon-query-bench:${{ steps.get_nqb_version.outputs.version }}
